"use server";

import { auth } from "@/auth";
import dbConnect from "@/lib/dbConnect";
import TrekRoute from "@/model/TrekRoute";

const trekRoutesMock = [
  {
    trekName: "Everest Base Camp Trek",
    startingPoint: "Lukla",
    destinationPoint: "Everest Base Camp",
    duration: { roundTrip: "12-14 days", oneWay: "6-7 days" },
    difficulty: "Difficult",
    elevation: { start: 2860, max: 5364, gain: 2500 },
    permits: [
      {
        name: "Sagarmatha National Park Permit",
        cost: "Rs. 3000",
        where: "Monjo or Kathmandu",
      },
      {
        name: "Khumbu Pasang Lhamu Rural Municipality Permit",
        cost: "Rs. 2000",
        where: "Lukla",
      },
    ],
    teahouses: {
      available: true,
      locations: ["Phakding", "Namche", "Dingboche", "Gorakshep"],
    },
    packingList: [
      "Down jacket",
      "Sleeping bag",
      "Water purifier",
      "Trekking poles",
    ],
    recommendedItinerary: [
      "Fly to Lukla and trek to Phakding",
      "Trek from Phakding to Namche Bazaar",
      "Acclimatization hike to Everest View Hotel and explore Namche",
      "Trek to Tengboche Monastery",
      "Trek to Dingboche",
      "Acclimatization hike to Nagarjun Hill or Chhukung",
      "Trek to Lobuche",
      "Trek to Gorakshep and hike to Everest Base Camp",
      "Hike to Kala Patthar and return to Pheriche",
      "Trek to Namche Bazaar",
      "Trek to Lukla",
      "Fly back to Kathmandu",
    ],
    bestSeason: ["March-May", "September-November"],
    highlights: ["Views of Everest", "Sherpa culture", "Tengboche Monastery"],
    safetyTips: [
      "Acclimatize properly",
      "Stay hydrated",
      "Beware of altitude sickness",
    ],
  },
  {
    trekName: "Annapurna Base Camp Trek",
    startingPoint: "Nayapul",
    destinationPoint: "Annapurna Base Camp",
    duration: { roundTrip: "7-10 days", oneWay: "4-5 days" },
    difficulty: "Moderate",
    elevation: { start: 1070, max: 4130, gain: 3060 },
    permits: [
      { name: "ACAP", cost: "Rs. 3000", where: "Pokhara or Nayapul" },
      { name: "TIMS", cost: "Rs. 1000", where: "Pokhara or Kathmandu" },
    ],
    teahouses: {
      available: true,
      locations: ["Ghandruk", "Chhomrong", "Deurali", "ABC"],
    },
    packingList: ["Rain jacket", "Headlamp", "Energy snacks", "Hiking boots"],
    recommendedItinerary: [
      "Drive to Nayapul and trek to Ghandruk",
      "Trek to Chhomrong",
      "Trek to Bamboo",
      "Trek to Deurali",
      "Trek to Annapurna Base Camp",
      "Trek back to Bamboo",
      "Trek to Jhinu Danda and enjoy hot springs",
      "Trek to Nayapul and drive back to Pokhara",
    ],
    bestSeason: ["March-May", "October-November"],
    highlights: ["Close-up view of Annapurna I", "Hot springs in Jhinu Danda"],
    safetyTips: [
      "Carry warm clothes",
      "Don’t rush ascent",
      "Watch out for leeches in monsoon",
    ],
  },
  {
    trekName: "Ghorepani Poon Hill Trek",
    startingPoint: "Nayapul",
    destinationPoint: "Poon Hill",
    duration: { roundTrip: "4-5 days" },
    difficulty: "Easy",
    elevation: { start: 1070, max: 3210 },
    permits: [
      { name: "ACAP", cost: "Rs. 3000", where: "Pokhara" },
      { name: "TIMS", cost: "Rs. 1000", where: "Pokhara" },
    ],
    teahouses: {
      available: true,
      locations: ["Tikhedhunga", "Ghorepani", "Ulleri"],
    },
    packingList: ["Walking stick", "Camera", "Warm layers"],
    recommendedItinerary: [
      "Drive to Nayapul and trek to Tikhedhunga",
      "Trek to Ghorepani",
      "Early morning hike to Poon Hill and return to Tadapani",
      "Trek to Ghandruk",
      "Return trek to Nayapul and drive to Pokhara",
    ],
    bestSeason: ["February-April", "September-November"],
    highlights: ["Sunrise view over Annapurna", "Rhododendron forests"],
    safetyTips: [
      "Carry enough water",
      "Trek early for sunrise",
      "Avoid slippery stones",
    ],
  },
  {
    trekName: "Langtang Valley Trek",
    startingPoint: "Syabrubesi",
    destinationPoint: "Kyanjin Gompa",
    duration: { roundTrip: "7-8 days" },
    difficulty: "Moderate",
    elevation: { start: 1460, max: 3870 },
    permits: [
      {
        name: "Langtang National Park Permit",
        cost: "Rs. 3000",
        where: "Dhunche",
      },
      { name: "TIMS", cost: "Rs. 1000", where: "Kathmandu" },
    ],
    teahouses: {
      available: true,
      locations: ["Lama Hotel", "Langtang", "Kyanjin Gompa"],
    },
    packingList: ["Map", "Sunscreen", "Daypack"],
    recommendedItinerary: [
      "Drive to Syabrubesi",
      "Trek to Lama Hotel",
      "Trek to Langtang Village",
      "Trek to Kyanjin Gompa",
      "Explore Kyanjin Ri or Tserko Ri",
      "Trek back to Lama Hotel",
      "Trek to Syabrubesi",
      "Drive to Kathmandu",
    ],
    bestSeason: ["March-May", "October-November"],
    highlights: ["Mountain views", "Tamang culture", "Glacier visits"],
    safetyTips: [
      "Watch for altitude sickness",
      "Stay on marked paths",
      "Check weather forecast",
    ],
  },
  {
    trekName: "Mardi Himal Trek",
    startingPoint: "Kande",
    destinationPoint: "Mardi Base Camp",
    duration: { roundTrip: "5-7 days" },
    difficulty: "Moderate",
    elevation: { start: 1700, max: 4500 },
    permits: [
      { name: "ACAP", cost: "Rs. 3000", where: "Pokhara" },
      { name: "TIMS", cost: "Rs. 1000", where: "Pokhara" },
    ],
    teahouses: {
      available: true,
      locations: ["Forest Camp", "Low Camp", "High Camp"],
    },
    packingList: ["Trekking shoes", "Buff", "Warm hat"],
    recommendedItinerary: [
      "Drive to Kande and trek to Forest Camp",
      "Trek to Low Camp",
      "Trek to High Camp",
      "Hike to Mardi Base Camp and return to High Camp",
      "Trek to Siding Village",
      "Drive back to Pokhara",
    ],
    bestSeason: ["March-May", "October-November"],
    highlights: ["Close-up views of Machhapuchhre", "Less crowded trail"],
    safetyTips: [
      "Avoid slippery grass",
      "Stay on ridge trail",
      "Start early to avoid clouds",
    ],
  },
  {
    trekName: "Manaslu Circuit Trek",
    startingPoint: "Soti Khola",
    destinationPoint: "Dharapani",
    duration: { roundTrip: "14-18 days" },
    difficulty: "Challenging",
    elevation: { start: 700, max: 5135, gain: 4400 },
    permits: [
      {
        name: "Manaslu Restricted Area Permit",
        cost: "USD 70+",
        where: "Kathmandu",
      },
      { name: "MCAP", cost: "Rs. 3000", where: "Kathmandu" },
      { name: "ACAP", cost: "Rs. 3000", where: "Kathmandu" },
    ],
    teahouses: {
      available: true,
      locations: ["Soti Khola", "Samagaun", "Lho", "Dharapani"],
    },
    packingList: ["Permit copies", "Insulated bottle", "Microspikes"],
    recommendedItinerary: [
      "Drive to Soti Khola",
      "Trek to Machha Khola",
      "Trek to Jagat",
      "Trek to Deng",
      "Trek to Namrung",
      "Trek to Samagaun",
      "Acclimatization day and optional Manaslu Base Camp hike",
      "Trek to Samdo",
      "Trek to Dharmashala",
      "Cross Larkya La Pass and trek to Bimtang",
      "Trek to Dharapani",
      "Drive to Besisahar and onward to Kathmandu",
    ],
    bestSeason: ["September-November", "March-May"],
    highlights: ["Remote villages", "Larkya La Pass", "Manaslu views"],
    safetyTips: ["Go with guide", "Check pass status", "Watch for snow & wind"],
  },
  {
    trekName: "Upper Mustang Trek",
    startingPoint: "Jomsom",
    destinationPoint: "Lo Manthang",
    duration: { roundTrip: "12-14 days" },
    difficulty: "Moderate",
    elevation: { start: 2700, max: 3840 },
    permits: [
      { name: "Upper Mustang Permit", cost: "USD 500", where: "Kathmandu" },
      { name: "ACAP", cost: "Rs. 3000", where: "Jomsom" },
    ],
    teahouses: {
      available: true,
      locations: ["Kagbeni", "Charang", "Lo Manthang"],
    },
    packingList: ["Windproof jacket", "Permit originals", "Power bank"],
    recommendedItinerary: [
      "Fly to Jomsom and trek to Kagbeni",
      "Trek to Chele",
      "Trek to Syangboche",
      "Trek to Ghami",
      "Trek to Tsarang",
      "Trek to Lo Manthang",
      "Explore Lo Manthang and nearby monasteries",
      "Trek to Yara or Chhoser",
      "Trek to Ghiling",
      "Trek to Chhuksang",
      "Trek to Jomsom",
      "Fly back to Pokhara",
    ],
    bestSeason: ["May-October"],
    highlights: ["Tibetan culture", "Walled city of Lo Manthang"],
    safetyTips: [
      "Respect local customs",
      "Expect dry winds",
      "Secure special permits",
    ],
  },
  {
    trekName: "Helambu Trek",
    startingPoint: "Sundarijal",
    destinationPoint: "Melamchi Pul",
    duration: { roundTrip: "5-7 days" },
    difficulty: "Easy",
    elevation: { start: 1400, max: 3600 },
    permits: [
      { name: "Shivapuri NP Permit", cost: "Rs. 1000", where: "Sundarijal" },
      { name: "TIMS", cost: "Rs. 1000", where: "Kathmandu" },
    ],
    teahouses: {
      available: true,
      locations: ["Chisapani", "Kutumsang", "Tarkeghyang"],
    },
    packingList: ["Day bag", "Rain cover", "Trail snacks"],
    recommendedItinerary: [
      "Drive to Sundarijal and trek to Chisapani",
      "Trek to Kutumsang",
      "Trek to Tharepati",
      "Trek to Tarkeghyang",
      "Trek to Sermathang",
      "Trek to Melamchi Pul and drive back to Kathmandu",
    ],
    bestSeason: ["March-May", "October-December"],
    highlights: ["Accessible from Kathmandu", "Cultural villages"],
    safetyTips: ["Carry a torch", "Avoid solo trekking"],
  },
  {
    trekName: "Kanchenjunga Base Camp Trek",
    startingPoint: "Taplejung",
    destinationPoint: "Pangpema",
    duration: { roundTrip: "20-25 days" },
    difficulty: "Extreme",
    elevation: { start: 1400, max: 5140 },
    permits: [
      {
        name: "Restricted Area Permit",
        cost: "USD 20/day",
        where: "Kathmandu",
      },
      { name: "KCAP", cost: "Rs. 3000", where: "Taplejung" },
    ],
    teahouses: { available: false, locations: [] },
    packingList: ["Tent", "Stove", "High-altitude gear"],
    recommendedItinerary: [
      "Drive to Taplejung",
      "Trek to Mitlung",
      "Trek to Chirwa",
      "Trek to Sekathum",
      "Trek to Amjilosa",
      "Trek to Gyabla",
      "Trek to Ghunsa",
      "Acclimatization at Ghunsa",
      "Trek to Kambachen",
      "Trek to Lhonak",
      "Trek to Pangpema (KBC)",
      "Return to Lhonak",
      "Trek to Ghunsa",
      "Trek back to Taplejung",
    ],
    bestSeason: ["October-November"],
    highlights: ["Massive glaciers", "Remote wilderness"],
    safetyTips: [
      "Trek with agency",
      "Carry altitude meds",
      "Know evacuation plans",
    ],
  },
  {
    trekName: "Dolpo Trek",
    startingPoint: "Juphal",
    destinationPoint: "Shey Gompa",
    duration: { roundTrip: "18-21 days" },
    difficulty: "Extreme",
    elevation: { start: 2500, max: 5200 },
    permits: [
      { name: "Upper Dolpo Permit", cost: "USD 500", where: "Kathmandu" },
      { name: "Shey Phoksundo NP Permit", cost: "Rs. 3000", where: "Dunai" },
    ],
    teahouses: { available: false, locations: [] },
    packingList: ["Mules for gear", "Solar charger", "Portable oxygen"],
    recommendedItinerary: [
      "Fly to Juphal and trek to Dunai",
      "Trek to Chhepka",
      "Trek to Jharana Hotel",
      "Trek to Phoksundo Lake",
      "Trek to Sallaghari",
      "Trek to Shey Gompa via Kang La Pass",
      "Explore Shey Gompa",
      "Return via same route",
    ],
    bestSeason: ["May-September"],
    highlights: ["Blue Phoksundo Lake", "Ancient monasteries"],
    safetyTips: [
      "Highly remote",
      "Trek with agency",
      "Carry altitude and emergency gear",
    ],
  },
];

export const seedTrekRoutes = async () => {
  try {
    const session = await auth();
    if (!session) return;
    await dbConnect();

    await TrekRoute.deleteMany();
    await TrekRoute.insertMany(trekRoutesMock);

    console.log("✅ 10 trek routes seeded!");
  } catch (err) {
    console.error("❌ Seeding error:", err);
  }
};
